name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: src/package-lock.json

    - name: Install dependencies
      working-directory: ./src
      run: |
        NODE_ENV=development npm ci
        npm install -D tailwindcss postcss autoprefixer

    - name: Build project
      working-directory: ./src
      env:
        NODE_ENV: production
      run: npm run build

    - name: Cache Next.js build
      uses: actions/cache@v4
      with:
        path: |
          ./src/.next/cache
          ./src/node_modules
        key: ${{ runner.os }}-nextjs-${{ hashFiles('src/package-lock.json') }}