name: Deploy to Staging

on:
  workflow_run:
    workflows: [ "Run Jest Tests" ]  
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: staging

    # steps:
    # - uses: actions/checkout@v3

    # - name: Deploy to Staging
    #   run: |
    #     vercel --token ${{ secrets.VERCEL_TOKEN }} --prod=false

    # - name: Validate Staging
    #   run: |
    #     curl -f https://staging.example.com/health || exit 1